### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by AndersonHJB** [JohannLai/gptcli#7]
这个其实就是把项目封装了 vue 静态项目，然后修改 key 就可以直接 build 是吧？生成静态网站，然后就可以部署。是这个原理？

**Comment by JohannLai** [comment]
hi @AndersonHJB  你好，不是哈～ 这个网站本质上是个命令行工具，他的官网是 powered by nextjs &  Tailwind & Vercel.

希望可以帮到你
