### ISSUE TITLE
Can gptcli commit generate based on the format of recent commit messages?

### ISSUE THREAD

**Issue by fatedier** [JohannLai/gptcli#8]
It would be even better if I could provide additional prompt information or conduct further optimization through dialogue when the results obtained are not very clear.

**Comment by JohannLai** [comment]
@fatedier This suggestion is very great！ I think it's good to further optimize this commit message through chat.  And  I will test whether generating commit messages based on recent commits is more accurate. If it's better, I will add a configuration that allows users to include the recent commit messages in the predicted commit message.
thanks a lot 👍👍👍

**Comment by JohannLai** [comment]
<img width="654" alt="image" src="https://user-images.githubusercontent.com/10769405/228179157-fab464cd-b4ab-456e-8d84-a8d7c3eb8845.png">

```sh
git commit -m':sparkles: Add Confirm and Input classes, prompt user input for
 confirm messages in Confirm class. Close issue #8.'
```

@fatedier Take a look, It it great!

**Comment by JohannLai** [comment]
[3.11.0](https://www.npmjs.com/package/@johannlai/gptcli/v/3.11.0)

Release！ 🎉

**Comment by fatedier** [comment]
Great! Works like a charm.

**Comment by JohannLai** [comment]
I will continue to tune this prompt 🤖

**Comment by fatedier** [comment]
https://github.com/JohannLai/gptcli/blob/main/src/plugins/commit.yml#L81

**Comment by JohannLai** [comment]
@fatedier thanks report the bug，I checked it today

**Comment by JohannLai** [comment]
fixed
